---
# tasks file for docker_ce
- name: Check if Swarm has already been Initialized
  shell: >
          docker info | egrep '^Swarm: ' | awk '{print $2}'
  register: swarm_status
  ignore_errors: true

- name: "Add Managers to the Swarm"
  shell: docker swarm join --token {{ token }} {{ address }}:2377
  when: "'inactive' in swarm_status.stdout_lines"
