---
# defaults file for security-firewalld
# Set default policy for INPUT and ACCEPT chains to DROP
firewall_default_drop: no

# Set default policy to DROP and only allow certain ICMP types
# instead of all ICMP traffic
firewall_strict: no

# Allow all ICMP traffic. Disabled if firewall_strict is True.
firewall_allow_icmp: yes

firewall_allowed_tcp_ports:
  - 22
firewall_allowed_udp_ports:
  - 161
firewall_rich_rules: []
  # - source:
  #   protocol:
  #   dest_port:
  #   new: yes

firewall_custom_iptables_rules: []

firewall_nat_rules: []
  # - family: ipv4
  #   original_port: 514
  #   protocol: udp
  #   translated_port: 5140

## For firewalld only
firewall_firewalld_rules: []
  # - immediate:
  #   interface:
  #   masquerade:
  #   permanent:
  #   port:                       # If port is specificed, protocol is required
  #   rich_rule:
  #   service:
  #   source:
  #   state: enabled
  #   timeout:
#   zone:
