---
# tasks file for basic_tools
- name: Install latest basic packages
  package:
          name: "{{ item.name }}"
          state: latest
  with_items: '{{ basic_packages }}'

- name: Install Latest EPEL Release
  yum:
          name: epel-release
          state: latest
  when:
          - ansible_distribution == "CentOS"

- name: "Cronjob Entry"
  cron:
    name: "{{ item.name }}"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    day: "{{ item.day }}"
    month: "{{ item.month }}"
    weekday: "{{ item.weekday }}"
    job: '{{ item.job }}'
  with_items: '{{ cronjobs }}'
  ignore_errors: true

- name: Update timezone to {{ timezone }}
  timezone:
          name: "{{ timezone }}"

- name: Colorizing terminal
  blockinfile:
          path: /etc/bashrc
          block: "{{ lookup('file', 'files/color_centos') }}"
  when:
          - ansible_distribution == "CentOS"

- name: Colorizing terminal
  blockinfile:
          path: /etc/bash.bashrc
          block: "{{ lookup('file', 'files/color_ubuntu') }}"
  when:
          - ansible_os_family == "Debian"
