---
- hosts: all
  gather_facts: true
  remote_user: meomeo
  become: true
  roles:
          - update_all
          - basic_tools
          - swapfile
          - security
          - linux-tuning
          - authorized_keys
