---
- hosts: DockerCluster
  gather_facts: true
  remote_user: meomeo
  become: true
  roles:
          #- update_all
            #- basic_tools
            #- swapfile
            #- security
          - linux-tuning
            #- authorized_keys
            #- docker_ce_install

- hosts: docker-manager-1
  remote_user: meomeo
  become: true
  roles:
          - docker_ce_swarm_init

- hosts: docker-managers
  remote_user: meomeo
  become: true
  vars:
          token: "{{ hostvars[groups['docker-manager-1'][0]]['manager_token']['stdout'] }}"
          address: "{{ hostvars[groups['docker-manager-1'][0]]['ansible_default_ipv4']['address'] }}"
  roles:
          - docker_ce_swarm_join

- hosts: docker-workers
  remote_user: meomeo
  become: true
  vars:
          token: "{{ hostvars[groups['docker-manager-1'][0]]['worker_token']['stdout'] }}"
          address: "{{ hostvars[groups['docker-manager-1'][0]]['ansible_default_ipv4']['address'] }}"
  roles:
          - docker_ce_swarm_join
