---
- hosts: esxi
  gather_facts: yes
  remote_user: root
  become: yes
  pre_tasks:
    - name: Install Python if not already present.
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
      ignore_errors: yes

    - name: Gather facts after Python is definitely present.
      setup:
  roles:
          #- update_all
          - basic_tools
          - swapfile
          - role: security-iptables
            iptables_custom_rules:
                    - name: tomcat-ports
                      rules: '-A INPUT -p tcp -m tcp --dport 8089 -j ACCEPT'
                      state: present
                    - name: mysql-ports
                      rules: '-A INPUT -p tcp -m tcp --dport 3306 -j ACCEPT'
                      state: present
          - linux-tuning
          - role: authorized_keys
            group_settings:
                    - { group: developer, state: present }
            user_settings:
                    - { user: duyvo, group: developer, state: present, remove: no, force: no }
                    - { user: vienle, group: developer, state: present, remove: no, force: no }
                    #- { user: hoangle, group: wheel, state: present, remove: no, force: no }
                    #- { user: sontruong, group: developer, state: absent, remove: no, force: no }
                    - { user: cuongle, group: developer, state: present, remove: no, force: no }
