---
- hosts: prod-db
  gather_facts: yes
  remote_user: centos
  become: yes
  pre_tasks:
    - name: Install Python if not already present.
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
      ignore_errors: yes

    - name: Gather facts after Python is definitely present.
      setup:

    - name: Install the MySQL repo.
      yum:
        name: http://repo.mysql.com/mysql80-community-release-el7-1.noarch.rpm
        state: present
      when: ansible_os_family == "RedHat"

    - name: Override variables for MySQL (RedHat).
      set_fact:
        mysql_daemon: mysqld
        mysql_packages: ['mysql-server']
        mysql_log_error: /var/log/mysqld.err
        mysql_syslog_tag: mysqld
        mysql_pid_file: /var/run/mysqld/mysqld.pid
        mysql_socket: /var/lib/mysql/mysql.sock
      when: ansible_os_family == "RedHat"
  roles:
          #- role: update_all
          #- role: basic_tools
          #- role: swapfile
          - role: service-mysql
            mysql_root_password: K00t0r0@)!(!
            mysql_databases:
                    - name: kootoro_admin
                      encoding: utf8mb4
                      collation: utf8mb4_0900_ai_ci
                    - name: kootoro_user
                      encoding: utf8mb4
                      collation: utf8mb4_0900_ai_ci
            mysql_users:
                    - name: 'k00t0r0'
                      host: '%'
                      password: 'K))t)r)135!#%'
                      priv: '*.*:ALL'
                      state: present
          - role: security-iptables
            iptables_custom_rules:
                    - name: backend-ips
                      rules: '-A INPUT -s 172.31.17.187/32 -p tcp -m tcp --dport 3306 -j ACCEPT'
                      state: present
                    - name: mysql-ports
                      rules: '-A INPUT -s 113.161.71.119/32 -p tcp -m tcp --dport 3306 -j ACCEPT'
                      state: present
          #- role: linux-tuning
          - role: authorized_keys
            group_settings:
                    - { group: developer, state: present }
            user_settings:
                    - { user: duyvo, group: developer, state: present, remove: no, force: no }
                    - { user: vienle, group: [ developer ], state: absent, remove: yes, force: yes }
                    - { user: hoangle, group: wheel, state: present, remove: no, force: no }
                    #- { user: sontruong, group: developer, state: absent, remove: no, force: no }
                    #- { user: cuongle, group: developer, state: present, remove: no, force: no }
