---
- hosts: prod-fe
  gather_facts: yes
  remote_user: centos
  become: yes
  pre_tasks:
    - name: Install Python if not already present.
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
      ignore_errors: yes

    - name: Gather facts after Python is definitely present.
      setup:
  roles:
          - role: update_all
          - role: basic_tools
            #- role: basic_tools
            #basic_packages:
            #        - { name: redis }
            #- role: services
            #services:
            #        - name: redis
            #          state: started
            #          enabled: yes
          - role: swapfile
          - role: security-iptables
            iptables_custom_rules:
                    - name: internal-ips
                      rules: '-A INPUT -s 172.31.0.0/16 -p tcp -m tcp -j ACCEPT'
                      state: present
            #        - name: tomcat-ports
            #          rules: '-A INPUT -p tcp -m tcp --dport 8089 -j ACCEPT'
            #          state: present
          - role: linux-tuning
          - role: authorized_keys
            group_settings:
                    - { group: developer, state: present }
                      #- { group: tomcat, state: present }
            user_settings:
                    - { user: duyvo, group: [ developer ], state: present, remove: no, force: no }
                      #- { user: vienle, group: [ developer, tomcat ], state: present, remove: no, force: no }
                    - { user: tunguyen, group: [ developer ], state: present, remove: no, force: no }
                    - { user: hoangle, group: wheel, state: present, remove: no, force: no }
                    #- { user: sontruong, group: developer, state: absent, remove: no, force: no }
                    #- { user: cuongle, group: developer, state: present, remove: no, force: no }

- hosts: prod-be
  gather_facts: yes
  remote_user: centos
  become: yes
  pre_tasks:
    - name: Install Python if not already present.
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
      ignore_errors: yes

    - name: Gather facts after Python is definitely present.
      setup:
  roles:
          - role: hostsfile
            hosts_entries:
                    - name: database
                      ip: 172.31.24.209
                      aliases:
                              - database.kootoro.com
          - role: update_all
          - role: basic_tools
            #- role: basic_tools
            #basic_packages:
            #        - { name: java }
            #        - { name: redis }
            #- role: services
            #services:
            #        - name: redis
            #          state: started
            #          enabled: yes
          - role: service-redis
            redis_requirepass: "fd085b92b30fe7d6493afadcc33a291936647d76af24d2db8d4ded8564653046"
          - role: service-tomcat
            tomcat_version: 9.0.13
            tomcat_permissions_production: True
            tomcat_users:
                    - username: "kootoro"
                      password: "e3420e31ad70b1c1df26a08463fddc4b93d2313d"
                      roles: "tomcat,admin,manager,manager-gui"
                    - username: "tomcat"
                      password: "50a50c8fc28eac48bea2480be3250187de12f013"
                      roles: "tomcat"
          - role: service-erlang
            erlang_version: "21.1.4"
          - role: service-rabbitmq
            rabbitmq_version: "3.7.9"
          - role: swapfile
          - role: security-iptables
            iptables_custom_rules:
                    - name: internal-ips
                      rules: '-A INPUT -s 172.31.0.0/16 -p tcp -m tcp -j ACCEPT'
                      state: present
                    - name: tomcat-ports
                      rules: '-A INPUT -p tcp -m tcp --dport 8080 -j ACCEPT'
                      state: present
            #        - name: mysql-ports
            #          rules: '-A INPUT -p tcp -m tcp --dport 3306 -j ACCEPT'
            #          state: present
                    - name: redis-ports
                      rules: '-A INPUT -p tcp -m tcp --dport 6379 -j ACCEPT'
                      state: present
          - role: linux-tuning
          - role: authorized_keys
            group_settings:
                    - { group: developer, state: present }
                      #- { group: tomcat, state: present }
            user_settings:
                    - { user: duyvo, group: [ developer ], state: present, remove: no, force: no }
                    - { user: vienle, group: [ developer, tomcat ], state: present, remove: no, force: no }
                    - { user: hoangle, group: wheel, state: present, remove: no, force: no }
                    #- { user: sontruong, group: developer, state: absent, remove: no, force: no }
                    #- { user: cuongle, group: developer, state: present, remove: no, force: no }

- hosts: prod-db
  gather_facts: yes
  remote_user: centos
  become: yes
  pre_tasks:
    - name: Install Python if not already present.
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
      ignore_errors: yes

    - name: Gather facts after Python is definitely present.
      setup:
  roles:
          - role: update_all
          - role: basic_tools
          - role: swapfile
          - role: security-iptables
            iptables_custom_rules:
                    - name: internal-ips
                      rules: '-A INPUT -s 172.31.0.0/16 -p tcp -m tcp -j ACCEPT'
                      state: present
                    - name: mysql-ports
                      rules: '-A INPUT -s 113.161.71.119/32 -p tcp -m tcp --dport 3306 -j ACCEPT'
                      state: present
          - role: linux-tuning
          - role: authorized_keys
            group_settings:
                    - { group: developer, state: present }
            user_settings:
                    - { user: duyvo, group: developer, state: present, remove: no, force: no }
                    - { user: vienle, group: [ developer ], state: absent, remove: yes, force: yes }
                    - { user: hoangle, group: wheel, state: present, remove: no, force: no }
                    #- { user: sontruong, group: developer, state: absent, remove: no, force: no }
                    #- { user: cuongle, group: developer, state: present, remove: no, force: no }
