---
# defaults file for service-erlang
erlang_daemon: erlang
erlang_state: present

erlang_version: ""

#erlang_rpm: "esl-erlang_{{ erlang_version }}-1~centos~{{ ansible_distribution_major_version }}_amd64.rpm"
#erlang_rpm_url: "https://packages.erlang-solutions.com/erlang/esl-erlang/FLAVOUR_1_general/{{ erlang_rpm }}"
erlang_rpm: "erlang-{{ erlang_version }}-1.el{{ ansible_distribution_major_version }}.{{ ansible_distribution | lower }}.x86_64.rpm"
erlang_rpm_url: "https://packagecloud.io/rabbitmq/erlang/packages/el/{{ ansible_distribution_major_version }}/{{ erlang_rpm }}/download"

#erlang_deb: "esl-erlang_{{ erlang_version }}-1~{{ ansible_distribution | lower }}~{{ ansible_distribution_release }}_amd64.deb"
#erlang_deb_url: "https://packages.erlang-solutions.com/erlang/esl-erlang/FLAVOUR_1_general/{{ erlang_deb }}"

