---
# handlers file for service-rabbitmq
- name: restart rabbitmq
  service: "name={{ rabbitmq_daemon }} state=restarted"
- name: Restart RabbitMQ server
  service:
    name: '{{ rabbitmq_daemon }}'
    state: restarted

- name: Reload systemd services and restart RabbitMQ
  systemd:
    name: '{{ rabbitmq_daemon }}'
    state: restarted
    daemon_reload: yes
