---
# defaults file for basic_tools
basic_packages:
        - { name: wget }
        - { name: telnet }
        - { name: tzdata }
        - { name: ntp }
        - { name: vim }
        - { name: net-tools }
timezone:
cronjobs:
        - { name: "Update Time", minute: "*/5", hour: "*", day: "*", month: "*", weekday: "*", job: "/usr/sbin/ntpdate asia.pool.ntp.org" }
