---
# tasks file for docker_ce
- name: Install docker-ce (RedHat)
  include: install-Rel.yml
  when:
          - ansible_os_family == 'RedHat'
          - ansible_distribution_major_version == '7'
  
- name: Install docker-ce (Ubuntu)
  include: install-Ubuntu.yml
  when:
          - ansible_distribution == 'Ubuntu'
          - ansible_lsb.major_release|int >= 14
  
- name: Enable Docker CE service on startup
  service:
          name: docker
          state: started
          enabled: yes
