---
# handlers file for security-firewalld

- name: reload firewall
  service:
          name: firewalld
          state: reloaded

- name: restart firewall
  service:
          name: firewalld
          state: restarted
