---
# tasks file for security-firewalld
- name: FIREWALLD | Start and enable firewalld
  service:
    name: firewalld
    enabled: yes
    state: started

- name: FIREWALLD | Open TCP ports in firewalld
  firewalld:
    permanent: "{{ item.permanent | default('yes') }}"
    state: enabled
    port: "{{ item.port | default(item) }}/tcp"
    zone: "{{ item.zone | default(omit) }}"
  with_items: "{{ firewall_allowed_tcp_ports }}"
  notify: restart firewall

- name: FIREWALLD | Open UDP ports in firewalld
  firewalld:
    permanent: "{{ item.permanent | default('yes') }}"
    state: enabled
    port: "{{ item.port | default(item) }}/udp"
    zone: "{{ item.zone | default(omit) }}"
  with_items: "{{ firewall_allowed_udp_ports }}"
  notify: restart firewall

- name: FIREWALLD | Configure NAT rules
  firewalld:
    state: enabled
    permanent: yes
    zone: "{{ item.zone | default(omit) }}"
    rich_rule: rule family={{ item.family | default('ipv4') }} forward-port port={{ item.original_port }} protocol={{ item.protocol }} to-port={{ item.translated_port }}
  with_items: "{{ firewall_nat_rules }}"
  notify: restart firewall

- name: FIREWALLD | Configure rich rules
  firewalld:
    state: enabled
    permanent: yes
    zone: "{{ item.zone | default(omit) }}"
    rich_rule: rule family={{ item.family | default('ipv4') }} port port={{ item.dest_port }} protocol={{ item.protocol }} source address={{ item.source }} accept
  with_items: "{{ firewall_rich_rules }}"

- name: FIREWALLD | Configure additional firewalld rules
  firewalld:
    immediate: "{{ item.immediate | default(omit) }}"
    interface: "{{ item.interface | default(omit) }}"
    masquerade: "{{ item.masquerade | default(omit) }}"
    permanent: "{{ item.permanent | default('yes') }}"
    port: "{{ item.port ~ '/' ~ item.protocol if (item.port is defined and item.protocol is defined) else omit }}"
    rich_rule: "{{ item.rich_rule | default(omit) }}"
    service: "{{ item.service | default(omit) }}"
    source: "{{ item.source | default(omit) }}"
    state: "{{ item.state | default('enabled') }}"
    timeout: "{{ item.timeout | default(omit) }}"
    zone: "{{ item.zone | default(omit) }}"
  with_items: "{{ firewall_firewalld_rules }}"
  notify: restart firewall
