version: '3.3'

networks:
  proxy:
    external:
      name: proxy

#configs:
#  traefik_toml_v2:
#    file: ./traefik.toml

services:
  traefik:
    image: traefik:1.7.4-alpine
    deploy:
      replicas: 3
      placement:
        constraints:
        - node.role == manager
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./acme.json:/acme.json
    - ./traefik.toml:/etc/traefik/traefik.toml
    networks:
    - proxy
    ports:
    - 80:80
    - 443:443
    - 8080:8080
#    configs:
#    - source: traefik_toml_v2
#      target: /etc/traefik/traefik.toml
#      mode: 444
    labels:
    #- traefik.frontend.entryPoints=http
    - traefik.frontend.rule=PathPrefix:/
    - traefik.frontend.rule=Host:traefik.meomeo.com
    - traefik.docker.network=proxy
    - traefik.port=8080
    - traefik.enable=true
