---
# tasks file for services

- name: Enable services on startup
  service:
          name: "{{ item.name }}"
          state: "{{ item.state | default('stopped') }}" 
          enabled: "{{ item.enabled | default('no') }}"
  with_items: "{{ services }}"
